server:
  port: 8088
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true # 接口404时抛出异常
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
mybatis-plus:
  mapperLocations: classpath:mapper/*.xml

swagger:
  swagger-open: false                #是否开启swagger (true/false)
